# Setup
title: 裴东宇
description: Chinese，山西太原，中北大学
url: https://dongyu-pei.github.io/-/
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg
description: dongyu pei 1826818087@qq.com

author:
  name: dongyu pei
  url: 
  email: 1826818087@qq.com
