# Setup
title: 裴东宇
description: Chinese，山西太原，中北大学
url: https://dongyu-pei.github.io/-/
avatar: /avatar.jpeg
permalink: pretty
cover_image: /bg.jpeg

author:
  name: dongyu pei
  email: 1826818087@qq.com
