# Setup
title: 裴东宇
description: 中北大学 · 计算机科学与技术学院 · 2024级研究生
url: https://dongyu-pei.github.io/-/
avatar: /avatar.jpeg
permalink: pretty
cover_image: /bg.jpeg

author:
  name: 裴东宇
  email: 1826818087@qq.com
